hostname: 172.17.0.3 # sudo docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' container_name
username: guest
password: guest
port: 5672

mysql_hostname: 172.17.0.2 # sudo docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' container_name
mysql_username: root
mysql_password: cloud123
mysql_database: cloud
mysql_port: 3306

