# Database Configuration:
cloud_hostname: 172.17.0.3 # sudo docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' container_name
cloud_username: guest
cloud_password: guest
cloud_port: 5672

edge_hostname: 172.17.0.3 # sudo docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' container_name
edge_username: guest
edge_password: guest
edge_port: 5672

cloud_mysql_hostname: 172.17.0.2 # sudo docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' container_name
cloud_mysql_username: root
cloud_mysql_password: cloud123
cloud_mysql_database: cloud
cloud_mysql_port: 3306

edge_mysql_hostname: 172.17.0.2 # sudo docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' container_name
edge_mysql_username: root
edge_mysql_password: cloud123
edge_mysql_database: cloud
edge_mysql_port: 3306
